### PR TITLE
I did sum new commandos

### PR DESCRIPTION
**Pull request by YazawaNic0**
Hugs, Kisses, Snuggles, Pats, Avatar URL, SeXUAL HArASSmesNTO

### CODE REVIEW

**Comment by apap04** [comment]
b ru h

**Comment by apap04** [comment]
dont change the prefix

**Comment by YazawaNic0** [comment]
i dont like owo

**Comment by YazawaNic0** [comment]
but ill change it

**Comment by apap04** [comment]
well

**Comment by apap04** [comment]
TOO BED

**Comment by YazawaNic0** [comment]
bed you say ;)

**Comment by apap04** [comment]
can you sign the cla at least

**Comment by YazawaNic0** [comment]
the fuc is that

**Comment by apap04** [comment]
read messages above

**Pull request closed without merging**
